site_name: Docker Containers
theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - yaml
    - bash
    - dockerfile

use_directory_urls: false
docs_dir: docs

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Docker Engine: docker-engine.md
  - Working with Images: working-with-images.md
  - Working with Containers: working-with-containers.md
  - Containerizing an Application: containerizing_an_app.md
  - Multi-container apps with Compose: multi-container-apps.md
  - Docker and Wasm: docker-and-wasm.md
  - Docker Swarm: docker-swarm.md
  - Docker Networking: docker-networking.md
  - Docker Volumes: docker-volumes.md
  - Docker Swecurity: docker-security.md
  - Docker CheatSheet: docker-cheatsheet.md

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - sane_lists
  - tables
  - toc:
      permalink: true

plugins:
  - search

extra:
  generator: false
