name: Deploy Documentation

on:
  push:
    branches:
      - master
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install MkDocs
        run: |
          pip install mkdocs

      - name: Build and Deploy MkDocs to GitHub Pages
        run: mkdocs gh-deploy --force
